import type { PhonemePool } from "@/lib/types";

export const englishPool: PhonemePool = {
  onsets: [
    "b",
    "c",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    "m",
    "n",
    "p",
    "r",
    "s",
    "t",
    "v",
    "w",
    "y",
    "z",
    "ch",
    "sh",
    "th",
    "pl",
    "gr",
    "cl",
    "dr",
    "fr",
    "pr",
    "sp",
    "st",
    "fl",
  ],
  nuclei: ["a", "e", "i", "o", "u", "ae", "ea", "io", "ai", "oo", "ou"],
  codas: ["t", "d", "k", "g", "p", "s", "m", "n", "r", "l", "th", "sh", "ck", "nt", "nd"],
};
